---
title: "Precip. Site Comparison"
author: "J. Bruce Bell"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/brbell01/Google Drive/PHD/CUNY/Research/Results/S1/angle_analysis/")
```

Import Libraries
```{r include=F}
libs <- c("tidyr","knitr","ggthemes","ggtext","stringr","dplyr","ggplot2","purrr","data.table","tibble","scales","grid", "sqldf")

# Loop through the vector and install and load each library if needed
for (lib in libs) {
  if (!require(lib, character.only = TRUE)) {
    install.packages(lib)
    library(lib, character.only = TRUE)
  }
}
```

Site 1: Data import and define parameters
```{r}
setwd("/Users/brbell01/Google Drive/PHD/CUNY/Research/Results/S1/angle_analysis/")
wd <- getwd()

# Import the data from the csv files
angle_v_VH <- read.csv(paste0(wd,"/angle_v_VH_scene155.csv")) %>% arrange(angle)
angle_v_VV <- read.csv(paste0(wd,"/angle_v_VV_scene155.csv")) %>% arrange(angle)
angle_v_VH_park <- read.csv(paste0(wd,"/angle_v_VH_rio_doce.csv")) %>% arrange(angle) %>% sample_frac(0.05)
angle_v_VV_park <- read.csv(paste0(wd,"/angle_v_VV_rio_doce.csv")) %>% arrange(angle) %>% sample_frac(0.05)

VH_data <- left_join(angle_v_VH, angle_v_VH_park, by="angle")
scope_names <- c("angle","scene 155", "PE Rio Doce") ; names(VH_data) <- scope_names
VH_data <- VH_data %>% pivot_longer(!angle, names_to = "scope", values_to = "value")

VV_data <- left_join(angle_v_VV, angle_v_VV_park, by="angle")
names(VV_data) <- scope_names
VV_data <- VV_data %>% pivot_longer(!angle, names_to = "scope", values_to = "value")

# ggplot() +
#   geom_point(data = VH_data, aes(x = angle, y = value, color = scope)) +
#   geom_point(data = VV_data, aes(x = angle, y = value, color = scope)) +
#   theme_minimal() +
#   labs(x = "Angle", y = "Value") 

```

Plot Site 1
```{r}
# Convert the scope factor to colors
VH_data$color <- ifelse(VH_data$scope == scope_names[2], "blue", "red")
VV_data$color <- ifelse(VV_data$scope == scope_names[2], "blue", "red")

# Sort VH_data and VV_data so that red plots on top of blue
VH_data <- VH_data[order(VH_data$color), ]
VV_data <- VV_data[order(VV_data$color), ]

# Compute trends
lm_VH <- lm(value ~ angle, data = VH_data[VH_data$scope == "PE Rio Doce", ])
lm_VV <- lm(value ~ angle, data = VV_data[VV_data$scope == "PE Rio Doce", ])
x_vals <- seq(35, 37, length.out = 100)
y_vals_VH <- coef(lm_VH)[1] + coef(lm_VH)[2] * x_vals
y_vals_VV <- coef(lm_VV)[1] + coef(lm_VV)[2] * x_vals

# Create the plot for VH_data
plot(VH_data$angle, VH_data$value, col = VH_data$color, xlab = "Angle", ylab = "backscatter (dB)", pch=3, ylim=c(-30,0))

# Add points for VV_data
points(VV_data$angle, VV_data$value, col = VV_data$color, pch=20)

# Add trend lines
# abline(lm_VH, lty = "dotted", col = "black", lwd = 1)
# abline(lm_VV, lty = "solid", col = "black", lwd = 1)
lines(x_vals, y_vals_VH, lty = "dotted", col = "red", lwd = 1)
lines(x_vals, y_vals_VV, lty = "solid", col = "red", lwd = 1)

#create legends
legend_VH <- paste("VH = ", round(coef(lm_VH)[2], 2), "*x + ", round(coef(lm_VH)[1], 2), ", R^2 = ", round(summary(lm_VH)$r.squared, 4))
legend_VV <- paste("VV = ", round(coef(lm_VV)[2], 2), "*x + ", round(coef(lm_VV)[1], 2), ", R^2 = ", round(summary(lm_VV)$r.squared, 4))

# Add a legend
#legend("topright", legend = scope_names[-1], fill = c("blue", "red"))
legend("bottomleft", legend = c(legend_VH, legend_VV), lty = c("solid", "dotted"), col = "red", cex = 0.8)
legend("bottomright", legend = c("scene 155", "PE Rio Doce"), fill = c("blue", "red"), cex = 0.8)
legend("topright", legend = c("VH", "VV"), pch = c(3, 20), cex = 0.7)
```

Site 2: Data import and define parameters
```{r}
# Import the data from the csv files
angle_v_VH <- read.csv(paste0(wd,"/angle_v_VH_scene82.csv")) %>% arrange(angle)
angle_v_VV <- read.csv(paste0(wd,"/angle_v_VV_scene82.csv")) %>% arrange(angle)
angle_v_VH_park <- read.csv(paste0(wd,"/angle_v_VH_sooretama.csv")) %>% arrange(angle) %>% sample_frac(0.05)
angle_v_VV_park <- read.csv(paste0(wd,"/angle_v_VV_sooretama.csv")) %>% arrange(angle) %>% sample_frac(0.05)

VH_data <- left_join(angle_v_VH, angle_v_VH_park, by="angle")
scope_names <- c("angle","scene 82", "REBIO Sooretama") ; names(VH_data) <- scope_names
VH_data <- VH_data %>% pivot_longer(!angle, names_to = "scope", values_to = "value")

VV_data <- left_join(angle_v_VV, angle_v_VV_park, by="angle")
names(VV_data) <- scope_names
VV_data <- VV_data %>% pivot_longer(!angle, names_to = "scope", values_to = "value")

# ggplot() +
#   geom_point(data = VH_data, aes(x = angle, y = value, color = scope)) +
#   geom_point(data = VV_data, aes(x = angle, y = value, color = scope)) +
#   theme_minimal() +
#   labs(x = "Angle", y = "Value") 

```

Plot Site 1
```{r}
# Convert the scope factor to colors
VH_data$color <- ifelse(VH_data$scope == scope_names[2], "blue", "red")
VV_data$color <- ifelse(VV_data$scope == scope_names[2], "blue", "red")

# Sort VH_data and VV_data so that red plots on top of blue
VH_data <- VH_data[order(VH_data$color), ]
VV_data <- VV_data[order(VV_data$color), ]

# Compute trends
lm_VH <- lm(value ~ angle, data = VH_data[VH_data$scope == "REBIO Sooretama", ])
lm_VV <- lm(value ~ angle, data = VV_data[VV_data$scope == "REBIO Sooretama", ])
x_vals <- seq(35, 37, length.out = 100)
y_vals_VH <- coef(lm_VH)[1] + coef(lm_VH)[2] * x_vals
y_vals_VV <- coef(lm_VV)[1] + coef(lm_VV)[2] * x_vals

# Create the plot for VH_data
plot(VH_data$angle, VH_data$value, col = VH_data$color, xlab = "Angle", ylab = "backscatter (dB)", pch=3, ylim=c(-30,0))

# Add points for VV_data
points(VV_data$angle, VV_data$value, col = VV_data$color, pch=20)

# Add trend lines
# abline(lm_VH, lty = "dotted", col = "black", lwd = 1)
# abline(lm_VV, lty = "solid", col = "black", lwd = 1)
lines(x_vals, y_vals_VH, lty = "dotted", col = "red", lwd = 1)
lines(x_vals, y_vals_VV, lty = "solid", col = "red", lwd = 1)

#create legends
legend_VH <- paste("VH = ", round(coef(lm_VH)[2], 2), "*x + ", round(coef(lm_VH)[1], 2), ", R^2 = ", round(summary(lm_VH)$r.squared, 4))
legend_VV <- paste("VV = ", round(coef(lm_VV)[2], 2), "*x + ", round(coef(lm_VV)[1], 2), ", R^2 = ", round(summary(lm_VV)$r.squared, 4))

# Add a legend
#legend("topright", legend = scope_names[-1], fill = c("blue", "red"))
legend("bottomleft", legend = c(legend_VH, legend_VV), lty = c("solid", "dotted"), col = "red", cex = 0.8)
legend("bottomright", legend = c("scene 82", "REBIO Sooretama"), fill = c("blue", "red"), cex = 0.8)
legend("topright", legend = c("VH", "VV"), pch = c(3, 20), cex = 0.7)
```

