---
title: "S1 Phenology Processing from Earth Engine"
author: "J. Bruce Bell"
date: "`r Sys.Date()`"
---

Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Imports
```{r echo=FALSE}
library(knitr)
library(tidyr)
library(lubridate)
library(scales)
library(ggthemes)
library(ggteqxt)
library(stringr)
library(dplyr)
library(ggplot2)
library(purrr)
library(data.table)
library(tibble)
library(geojsonio)
library(sf)
library(tidyquant)
library(circular)
```

Parameters
```{r}
#working directory
#setwd("/Users/brbell01/Google Drive/PHD/CUNY/Research/R/Phenology/raw/")
wd <- "/Users/brbell01/Google Drive/PHD/CUNY/Research/R/Phenology/raw"

#data descriptors
studyarea_base <- "rio_doce" # "mata_escura" ; "monte_pascoal" ; "rio_doce" ; "sooretama"
bandname <- "RVI"  # "VH" ; "VV"  ; "VHVV_ratio" "RVI"
```

```{r}
#define function for parsing the nested geojson strings
geojson_to_df <- function(str) {
              str %>% 
              str_remove_all('\\"') %>% 
              str_remove_all(" ") %>% 
              str_remove_all("\\]") %>% 
              str_remove_all("\\[") -> tab
              return(read.table(text=tab, col.names = c("date", bandname
                                ,paste0(bandname,"_sd")
                                ), sep = ","))
}     
```

Import Sentinel-1 data
```{r}
#gather files for each year
tables_yrslist <- dir(paste0(wd, "/s1/1ha/second_run"), full.names = T, pattern = "geojson") %>% str_subset(studyarea_base) 

#process files in a loop
indexdata <- data.frame()
IDs <- st_read(tables_yrslist[1]) %>% st_drop_geometry()
IDs <- as.vector(IDs[[1]])
#IDs <- c("1", "3", "4", "6", "7", "8", "9", "11", "12", "13", "15", "16", "17", "18", "19", "21", "22", "23", "24", "26", "27", "28", "29", "30", "31", "32", "33", "35", "36", "37", "38", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "58", "59", "60", "61", "62", "63", "64", "66", "67", "68", "69", "71", "72", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "104", "105", "107", "108", "109", "110", "112", "113", "115", "116", "117", "118", "119", "120", "121", "123", "124", "125", "126", "127", "128", "129", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "144", "146", "147", "148", "149", "150")

#IDs <- c("3", "5", "7", "8", "9", "10", "11", "17", "21", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "37", "39", "41", "42", "43", "44", "46", "47", "48", "50", "51", "53", "55", "56", "58", "59", "60", "61", "63", "64", "65", "66", "67", "68", "69", "71", "72", "75", "76", "77", "78", "79", "80", "81", "82", "85", "86", "87", "88", "89", "91", "92", "94", "96", "97", "98", "99", "101", "103", "108", "109", "110", "111", "112", "114", "115", "117", "118", "119", "120", "123", "124", "125", "126", "127", "131", "132", "133", "135", "136", "137", "138", "139", "140", "142", "143", "144", "146", "147", "148")

for (year in 1:length(tables_yrslist)) {
      table <- st_read(tables_yrslist[year]) %>% st_drop_geometry()
      table <- unlist(table[bandname])
    
      #loop through a geojson file and merge time series samples together by Hectare_ID 
      table <- lapply(table,geojson_to_df) # process dataframes
  
      for (i in 1:length(table)) {
            table[[i]]$date <- ymd(table[[i]]$date) # format date
            table[[i]][2:3] <- table[[i]][2:3] %>% mutate(across(everything(),as.numeric))
            # group and average 2 samples taken by overlapping S-2 scenes (North & South).
            # Also, consider separating tables by scene to compare effect of viewing
            # angle on index values.
             table[[i]] <- table[[i]] %>% group_by(date) 
             table[[i]] <- table[[i]] %>% summarize(mean =        
                               mean(.data[[bandname]], na.rm = TRUE)
                               , sd = mean(.data[[paste0(bandname,"_sd")]], na.rm = TRUE)
                               )
            }         
      table <- reduce(table, full_join, by = "date")  %>% arrange(date)  # merge by date
  
      #update the master table with processed data for each year by row bind
      indexdata <- rbindlist(list(indexdata,table))
}

#set column names
colnames <- c()
colnames <- lapply(1:length(IDs), function(id) {
  IDpair <- c(paste0(bandname,"_hectareID_", as.character(IDs)[id])  #set column names
              ,paste0(bandname,"_sd_hectareID_", as.character(IDs)[id])) 
            colnames <- append(colnames, IDpair)
            }) %>% 
   unlist
colnames <- c("date", colnames)
names(indexdata) <- colnames
```

```{r}
#write out processed file
filename_base <- paste0(studyarea_base, "_s1_1ha_", bandname)
write.csv(indexdata, paste0(wd, "/s1/1ha/second_run/", filename_base, "_processed.csv"))
```
