---
title: "S1 vs Topographic Slope Exploration"
author: "J. Bruce Bell"
date: "`r Sys.Date()`"
---

Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Imports
```{r include=FALSE}
packages <- c("knitr", "tidyr", "lubridate", "scales", "ggthemes", "ggtext", "stringr", "dplyr", "ggplot2", "data.table", "tibble", "sf", "tidyquant", "purrr", "ggpubr")

installed_packages <- rownames(installed.packages())
for (package in packages) {
  if (!(package %in% installed_packages)) {
    install.packages(package)
  }
  library(package, character.only = TRUE)
}
```

```{r}
#working directory
wd <- "/Users/brbell01/Documents/git/atlantic_forest_phenology/R/raw/s1/1ha/second_run/"
```

Import processed Sentinel-1 data tables
```{r}
#Parameters to be altered
foresttype <-  "Seasonal Semi-deciduous Forest"  # "Seasonal Semi-deciduous Forest"  ; "Broadleaf Evergreen"
studyarea <- "REBIO Sooretama, ES" #  "PE Rio Doce, MG"  # "REBIO Mata Escura, MG"  # ; "PNH Monte Pascoal, BA" ; "REBIO Sooretama, ES"
studyarea_list <- c("sooretama" , "rio_doce" , "mata_escura" , "monte_pascoal")
band.list <- c("VH", "VV", "RVI")

#import
masterdata_list <- vector(mode = "list", length = 0)

for (band in band.list) {
indexdata <- slope_table <- data.frame(matrix(nrow=0, ncol=2)) ; names(slope_table) <- c("Hectare_ID", "value")
for (studyarea_base in studyarea_list) {
      table <- read.csv(paste0(wd, studyarea_base, "_s1_1ha_", band, "_processed.csv"))
      table <- table[,!names(table) %in% c("X")] %>% mutate(date = ymd(date))
      table <- table %>% filter(date < as.Date('2017-01-01')) %>% gather("Hectare_ID", value, -date) %>% filter(!grepl('sd', Hectare_ID)) %>% group_by(Hectare_ID) %>% summarize(mean(value, na.rm=TRUE), sd(value,na.rm=TRUE)) %>% mutate(site_name = studyarea_base)
      names(table)[2] <- "value"  ; names(table)[3] <- "sd"
      indexdata <- rbind(indexdata, table)
      indexdata <- indexdata %>% mutate(Hectare_ID = Hectare_ID %>% gsub("[^0-9.]", "", .))
}
masterdata_list[[band]] <- indexdata 
}


```

```{r}
#define function for parsing the nested geojson strings
geojson_to_df <- function(str) {
              str %>% 
              str_remove_all('\\"') %>% 
              str_remove_all(" ") %>% 
              str_remove_all("\\]") %>% 
              str_remove_all("\\[") -> tab
              return(read.table(text=tab, sep = ","))
}     
```

Import slope data
```{r}
#import
slope_table <- data.frame(matrix(nrow=0, ncol=3)) ; names(slope_table) <- c("Hectare_ID", "slope_mean", "site_name")

for (studyarea_base in studyarea_list) {
studyarea_slopes <- read.csv(paste0("/Users/brbell01/Google Drive/PHD/CUNY/Research/Data/Raster/STRM/plot_means/", studyarea_base, "_Hectare_means.csv"))

#process slope_list
studyarea_slopes <- lapply(studyarea_slopes,geojson_to_df)
studyarea_slopes <- data.frame(cbind(studyarea_slopes$Hectare_ID$V1, studyarea_slopes$mean$V1, studyarea_base))
names(studyarea_slopes) <- c("Hectare_ID", "slope_mean", "site_name")
slope_table <- rbind(slope_table, studyarea_slopes)
slope_table$slope_mean <- slope_table$slope_mean %>% as.numeric()
}

```

Plot Mean Backscatter
```{r}
# Choose Index 
index_data <- masterdata_list$RVI
#join table 
data <- left_join(index_data, slope_table, by=c("Hectare_ID","site_name"))

index_data <- index_data %>% select(-sd)
index_data <- index_data %>% mutate(RVI_mean = value)
data <- data %>% mutate(RVI_mean = value)
data <- left_join(data, index_data, by=c("Hectare_ID","site_name"))

data <- data %>% select(-c(value.x, value.y, sd))

#write.csv(data, file = "S1_vs_slope.csv")

data <- data %>% filter(site_name == "rio_doce"| site_name == "sooretama")
data$point_shape <- ifelse(data$site_name == "rio_doce", 16, 17)

ggplot(data = data, aes(x = slope_mean, y = RVI_mean.x, color = site_name)) +
  geom_point(aes(shape = factor(point_shape))) +  # Use different shapes for the points (16 and 17)
  # geom_text(data = subset(data, sd > 1.2),
  #          aes(label = Hectare_ID), size = 2.5, position = position_nudge(y = -0.07)) +
  ylab("Mean RVI index") +
  xlab("mean slope (degrees)") +
  geom_smooth(method = "lm", se = FALSE,formula = y ~ x) +
  stat_cor(aes(label = paste(..rr.label..)),  # add R^2 value
           r.accuracy = 0.001,
           label.x = 10) +
  stat_regline_equation(aes(label = ..eq.label..),  # add equation to linear regression
                        label.x = 5) +
  theme_pubr() +
  xlim(0, 15)
```

Plot Variance in Backscatter
```{r}
# Choose Index 
index_data <- masterdata_list$RVI
#join table 
data <- left_join(index_data, slope_table, by=c("Hectare_ID","site_name"))

index_data <- index_data %>% select(-value)
index_data <- index_data %>% mutate(RVI_sd = sd)
data <- data %>% mutate(RVI_sd = sd)
data <- left_join(data, index_data, by=c("Hectare_ID","site_name"))

data <- data %>% select(-c(sd.x, sd.y, value))

#write.csv(data, file = "S1_vs_slope.csv")

data <- data %>% filter(site_name == "rio_doce"| site_name == "sooretama")
data$point_shape <- ifelse(data$site_name == "rio_doce", 16, 17)

ggplot(data = data, aes(x = slope_mean, y = RVI_sd.x, color = site_name)) +
  geom_point(aes(shape = factor(point_shape))) +  # Use different shapes for the points (16 and 17)
  # geom_text(data = subset(data, sd > 1.2),
  #          aes(label = Hectare_ID), size = 2.5, position = position_nudge(y = -0.07)) +
  ylab("Variance (sd) in RVI index value ") +
  xlab("mean slope (degrees)") +
  geom_smooth(method = "lm", se = FALSE,formula = y ~ x) +
  stat_cor(aes(label = paste(..rr.label..)),  # add R^2 value
           r.accuracy = 0.001,
           label.x = 10) +
  stat_regline_equation(aes(label = ..eq.label..),  # add equation to linear regression
                        label.x = 5) +
  theme_pubr() +
  xlim(0, 15)
```

Save Plot
```{r}
ggsave("S1_RVI_vs_topographic_slope.png", units="in", width=7, height=7, dpi=300, device = 'png')
```

